### ISSUE TITLE
NoMethodError (undefined method `project' for nil:NilClass)

### ISSUE THREAD

**Issue by farinpl** [future-architect/redmine_slack_integration#9]
Hello! 

I wanted to try out your Redmine Plugin  but the following error occurs when I try to edit an issue (I followed the installation guide). 

<img width="604" alt="Bildschirmfoto 2022-06-17 um 00 00 33" src="https://user-images.githubusercontent.com/16154371/174185605-59648db6-6008-4636-bc14-f9430beb8777.png">
**production.log**

```
DEBUG> issue id: 5951
DEBUG> issues status id: 5
DEBUG> issue subject: slack test1
DEBUG> journal id: 20159
DEBUG> journal notes:

NoMethodError (undefined method `project' for nil:NilClass):

plugins/redmine_checklists/lib/redmine_checklists/patches/issues_helper_patch.rb:39:in `details_to_strings_with_checklists'
plugins/redmine_slack_integration/lib/redmine_slack_integration/hooks.rb:142:in `controller_issues_edit_after_save'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:93:in `call_hook'
app/controllers/issues_controller.rb:589:in `block in save_issue_with_child_records'
app/controllers/issues_controller.rb:575:in `save_issue_with_child_records'
app/controllers/issues_controller.rb:172:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
**My System:**
Ubuntu 20.04 
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
 
<img width="643" alt="Bildschirmfoto 2022-06-17 um 00 00 01" src="https://user-images.githubusercontent.com/16154371/174185582-43f20c98-7644-4fb2-9710-d7df6c61b90c.png">

Do you have any idea what could be the problem here? 

Quick update:
It's possible to create an new issue without problems in redmine and the notification via slack is working. But when I try to edit this new issue (for example setting the issue to done) the error occurs.

**Comment by farinpl** [comment]
The problem was solved. The reason for the problem was the Redmine Checklists plugin (v. 3.1.18) and was solved with an update of the Redmine Checklists plugin (v. 3.1.21).
